### ISSUE TITLE
Add note in README about the c-frame fork

### ISSUE THREAD

**Issue by vincentfretin** [n5ro/aframe-physics-system#206]
Hello @n5ro, we created a fork in the c-frame organization https://github.com/c-frame/aframe-physics-system before you gave me access to the repo. The fork has now had a lot of updates to work with latest aframe.
@diarmidmackenzie will create a PR here to add a note in the README to point to the maintained c-frame fork and I'll merge it.
Can you give me vincentfretin and diarmidmackenzie permission on npm so we can release a version that also includes this note?
Can you also add diarmidmackenzie for aframe-extras on npm so I'm not the only one. Thanks!

**Comment by n5ro** [comment]
You both (vincentfretin and diarmidmackenzie) are now invited to
aframe-extras and aframe-physics-system on npm.



Sincerely,


Micah Blumberg,

Links
github.com/n5ro
github.com/micah1
github.com/v5ma/selfawarenetworks
Featured articles, bio, and ways to connect: http://vrma.io
Main articles http://svgn.io

**Comment by vincentfretin** [comment]
Thank you!

**Comment by diarmidmackenzie** [comment]
I've done this & pushed the updated version to npm so that the note is visible there too.
